### ISSUE TITLE
validate Admin

### ISSUE THREAD

**Issue by eDnS** [daveismynamecom/loginregister#1]
hello,
I would like to know how to perform the addition of account validation but only by an admin with sending mail to the user that the account is validated please?

sorry for my English

**Comment by kodaje** [comment]
Hi, I would like to insert and display the firstname and lastname of the user but i dont know what is the variable that is missing. This is the error displayed "SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens".Need assistance.Tq

**Comment by daveismyname** [comment]
Sorry for late response since this was so long ago I'm closing this issue, if you still have this problem let me know.
