### ISSUE TITLE
Registration success but not getting email

### ISSUE THREAD

**Issue by abstractindia** [daveismynamecom/loginregister#6]
Hi, Dave. I am able to register but the email is never received. Its on a live server with email configured, here is the link http://goo.gl/lhxise
Please advise. If any other details needed please let me know.

**Comment by abstractindia** [comment]
Any updates?

**Comment by abstractindia** [comment]
Sir, Waiting your reply.

**Comment by daveismyname** [comment]
I've added phpmailer to this for sending out emails please download the files again and try it again if your email is still not getting through I recommend using mandrill (https://www.mandrill.com) you can use that to deliver the email via SMTP.

To use it create an account then get the API username and password then put that into classes/phpmailer/mail.php

**Comment by abstractindia** [comment]
Ya. Now its working fine with option to send html email. Thanks.

**Comment by zazasco** [comment]
i uploaded the files its diplaying email confirmation sent but am not getting the email, i have edited SMTP connection details
